[package]
name = "skytable"
version = "0.2.3"
authors = ["Sayan Nandan <nandansayan@outlook.com>"]
edition = "2018"
readme = "README.md"
description = "Official Rust client driver for Skytable"
license = "Apache-2.0"
documentation = "https://docs.rs/skytable"
repository = "https://github.com/skytable/client-rust"
categories = []
keywords = ["skytable", "driver", "client", "database", "nosql"]

[features]
default = []
async = ["tokio", "bytes"]
sync = []

[dependencies]
bytes = { version="1.0.1", optional=true }
tokio = { version = "1.5.0", features = ["net", "io-util", "io-std"], optional=true }

[dev-dependencies]
tokio = {version="1.5.0", features=["rt-multi-thread", "macros"]}